[package]
name = "sync"
version = "0.1.0"
authors = ["user <no email given>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gethostname = "0.2.1"
lazy_static = "1.4.0"
eyre = "0.6.8"
